name: oak_build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'oak'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install NPM dependencies
        run: npm install
      - name: Build source code
        run: npm run build
